[2024-04-02 13:14:21,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 13:14:21,056] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 13:14:21,057] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:14:21,057] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 13:14:21,057] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:14:21,080] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 13:14:21,087] {standard_task_runner.py:52} INFO - Started process 13932 to run task
[2024-04-02 13:14:21,092] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpmp52j_h1', '--error-file', '/tmp/tmpy0z8ln62']
[2024-04-02 13:14:21,094] {standard_task_runner.py:80} INFO - Job 263: Subtask AAPL
[2024-04-02 13:14:21,150] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 13:14:21,226] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 13:14:22,092] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-03-29 -> 2024-03-30)
[2024-04-02 13:14:22,097] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 13:14:22,108] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240402T161421, end_date=20240402T161422
[2024-04-02 13:14:22,158] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 13:14:22,186] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:20:23,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 17:20:23,585] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 17:20:23,585] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:20:23,585] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:20:23,585] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:20:23,619] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 17:20:23,641] {standard_task_runner.py:52} INFO - Started process 9856 to run task
[2024-04-02 17:20:23,665] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzr_i_rsn', '--error-file', '/tmp/tmpnkvuuui2']
[2024-04-02 17:20:23,668] {standard_task_runner.py:80} INFO - Job 247: Subtask AAPL
[2024-04-02 17:20:23,962] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:20:24,220] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 17:20:24,846] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:20:24,875] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240402T202023, end_date=20240402T202024
[2024-04-02 17:20:24,903] {standard_task_runner.py:92} ERROR - Failed to execute job 247 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 9856)
[2024-04-02 17:20:24,935] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:20:25,005] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:48:22,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 17:48:22,186] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 17:48:22,186] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:48:22,187] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:48:22,187] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:48:22,214] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 17:48:22,227] {standard_task_runner.py:52} INFO - Started process 25456 to run task
[2024-04-02 17:48:22,242] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '507', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdtbzgxee', '--error-file', '/tmp/tmpl68y2akv']
[2024-04-02 17:48:22,244] {standard_task_runner.py:80} INFO - Job 507: Subtask AAPL
[2024-04-02 17:48:22,410] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:48:22,587] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 17:48:23,294] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:48:23,325] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240402T204822, end_date=20240402T204823
[2024-04-02 17:48:23,347] {standard_task_runner.py:92} ERROR - Failed to execute job 507 for task AAPL (index 0 is out of bounds for axis 0 with size 0; 25456)
[2024-04-02 17:48:23,379] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:48:23,472] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 19:16:57,182] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 19:16:57,197] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 19:16:57,197] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 19:16:57,197] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 19:16:57,198] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 19:16:57,232] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 19:16:57,240] {standard_task_runner.py:52} INFO - Started process 16633 to run task
[2024-04-02 19:16:57,266] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '609', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp3g858eej', '--error-file', '/tmp/tmpj81z7ick']
[2024-04-02 19:16:57,268] {standard_task_runner.py:80} INFO - Job 609: Subtask AAPL
[2024-04-02 19:16:57,450] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 19:16:57,624] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 19:16:58,540] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-03-29 -> 2024-03-30)
[2024-04-02 19:16:58,596] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 19:16:58,699] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240402T221657, end_date=20240402T221658
[2024-04-02 19:16:58,764] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 19:16:58,881] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 20:41:02,524] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 20:41:02,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 20:41:02,548] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 20:41:02,548] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 20:41:02,549] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 20:41:02,594] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 20:41:02,629] {standard_task_runner.py:52} INFO - Started process 28123 to run task
[2024-04-02 20:41:02,667] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpbnwzuarz', '--error-file', '/tmp/tmp2k1n_4_z']
[2024-04-02 20:41:02,675] {standard_task_runner.py:80} INFO - Job 708: Subtask AAPL
[2024-04-02 20:41:02,812] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 20:41:02,970] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 20:41:03,701] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-03-29 -> 2024-03-30)
[2024-04-02 20:41:03,706] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 20:41:03,743] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240402T234102, end_date=20240402T234103
[2024-04-02 20:41:03,814] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 20:41:03,904] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 21:57:24,511] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 21:57:24,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 21:57:24,528] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 21:57:24,528] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 21:57:24,529] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 21:57:24,548] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 21:57:24,558] {standard_task_runner.py:52} INFO - Started process 55964 to run task
[2024-04-02 21:57:24,565] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '899', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpqpuh067d', '--error-file', '/tmp/tmp155smuti']
[2024-04-02 21:57:24,569] {standard_task_runner.py:80} INFO - Job 899: Subtask AAPL
[2024-04-02 21:57:24,706] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 21:57:24,835] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 21:57:25,479] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-03-29 -> 2024-03-30)
[2024-04-02 21:57:35,498] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 21:57:35,554] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240403T005724, end_date=20240403T005735
[2024-04-02 21:57:35,635] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 21:57:35,740] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 23:19:06,897] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 23:19:06,919] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02 23:19:06,920] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 23:19:06,920] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 23:19:06,920] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 23:19:06,955] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2024-03-30 00:00:00+00:00
[2024-04-02 23:19:06,966] {standard_task_runner.py:52} INFO - Started process 86321 to run task
[2024-04-02 23:19:06,976] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '1197', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpp3m2d1i6', '--error-file', '/tmp/tmppb7uvfcd']
[2024-04-02 23:19:06,979] {standard_task_runner.py:80} INFO - Job 1197: Subtask AAPL
[2024-04-02 23:19:07,116] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2024-03-30T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 23:19:07,280] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-03-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-30T00:00:00+00:00
[2024-04-02 23:19:07,852] {history.py:222} ERROR - AAPL: No price data found, symbol may be delisted (1h 2024-03-29 -> 2024-03-30)
[2024-04-02 23:19:17,867] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 23:19:17,923] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20240330T000000, start_date=20240403T021906, end_date=20240403T021917
[2024-04-02 23:19:18,015] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 23:19:18,093] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
